# -*- coding: utf-8 -*-
"""Pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OX0xlccdgmN8HAKBOfjvnufqV_jAmKyB
"""

import pandas as pd
import random

# Lista de nombres y apellidos ficticios
nombres = ['Juan', 'Maria', 'Pedro', 'Ana', 'Luisa', 'Carlos', 'Laura', 'Diego', 'Sofia', 'Manuel', 'Lucia', 'Daniel', 'Elena', 'Javier', 'Carmen', 'Alejandro', 'Isabel', 'Miguel', 'Raquel', 'Antonio']
apellidos = ['Martinez', 'Gomez', 'Rodriguez', 'Fernandez', 'Diaz', 'Perez', 'Ruiz', 'Gonzalez', 'Alvarez', 'Gutierrez', 'Torres', 'Moreno', 'Jimenez', 'Vazquez', 'Ramos', 'Martin', 'Sanchez', 'Lopez', 'Ortega', 'Navarro']

# Lista de asignaturas ficticias
asignaturas = ['Matematicas', 'Literatura', 'Ciencias', 'Inglés', 'Historia', 'Geografía', 'Arte', 'Física', 'Educación Física', 'Química', 'Economía', 'Sociología', 'Psicología', 'Filosofía', 'Informática', 'Biología', 'Matemáticas Aplicadas', 'Programación', 'Robótica', 'Dibujo Técnico']

# Generar datos ficticios para 100 estudiantes
datos_estudiantes = []
for _ in range(100):
    nombre = random.choice(nombres)
    apellido = random.choice(apellidos)
    asignatura = random.choice(asignaturas)
    nota = random.randint(50, 100)  # Nota aleatoria entre 50 y 100
    datos_estudiantes.append([nombre, apellido, asignatura, nota])

# Crear un DataFrame de Pandas con los datos y agregar encabezados
df = pd.DataFrame(datos_estudiantes, columns=['nombre', 'apellido', 'asignatura', 'nota'])

# Guardar el DataFrame en un archivo CSV
df.to_csv('datos_estudiantes.csv', index=False)
df.describe()